### ISSUE TITLE
Suddenly stopped working?

### ISSUE THREAD

**Issue by roko-p** [bbeck/keyboard-shortcuts-for-google-search#7]
Has anyone had a similar issue? I installed Windows 8.1 a couple of days ago, had it working for a day, and then the awesome little arrow disappeared :confused: (and also if I hit Enter, it doesn't open the first result)
(Both in Chrome's _Windows 8 mode_ and _Desktop mode_)

Had it reloaded, disabled/enabled, removed and reinstalled, and still nothing... I can't figure out what I'm doing wrong or what I did that caused the extension to stop working.

Chrome (Version 38.0.2125.111 m) is still constantly notifying me to disable developer mode extensions (this is the only one I have), but it's not working :disappointed:

**Comment by bbeck** [comment]
It's been working fine for me on OS X with Chrome 38.0.2125.104.

**Comment by roko-p** [comment]
(The problem was that chrome switched me from _google.com_ to _google.hr_, so I just added that as well to `content_scripts.matches` in manifest.json. Thanks :) )
